using UnityEngine;

namespace GameplayMechanicsUMFOSS.Samples.SceneManagerSample
{
    /// <summary>
    /// Sits next to a FoodSpawner and assigns its apple/bomb factory delegates at
    /// runtime. Builds single-sprite pickups using the pixel-art Apple.png and
    /// Bomb.png assets generated by the editor generator. No glow halos — clean
    /// flat retro aesthetic.
    /// </summary>
    [RequireComponent(typeof(FoodSpawner))]
    public class FoodFactoryBootstrap : MonoBehaviour
    {
        private static Sprite appleSprite;
        private static Sprite bombSprite;

        private void Awake()
        {
#if UNITY_EDITOR
            if (appleSprite == null)
                appleSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>("Assets/SceneManagerDemo/Apple.png");
            if (bombSprite == null)
                bombSprite = UnityEditor.AssetDatabase.LoadAssetAtPath<Sprite>("Assets/SceneManagerDemo/Bomb.png");
#endif
            if (appleSprite == null) appleSprite = Resources.Load<Sprite>("Apple");
            if (bombSprite == null) bombSprite = Resources.Load<Sprite>("Bomb");

            var spawner = GetComponent<FoodSpawner>();
            spawner.appleFactory = BuildApple;
            spawner.bombFactory = BuildBomb;
        }

        private GameObject BuildApple()
        {
            var go = new GameObject("Strawberry");
            // Sprite is already imported at CellSize * 1.20 — no halo, no extra scale
            var sr = go.AddComponent<SpriteRenderer>();
            sr.sprite = appleSprite;
            sr.sortingOrder = 10;
            go.AddComponent<Apple>();
            return go;
        }

        private GameObject BuildBomb()
        {
            var go = new GameObject("Bomb");
            // Sprite is already imported at CellSize * 1.20 — no halo, no extra scale
            var sr = go.AddComponent<SpriteRenderer>();
            sr.sprite = bombSprite;
            sr.sortingOrder = 10;
            go.AddComponent<Bomb>();
            return go;
        }
    }
}
